[versions]
archloom = "1.13.44"
archloomPack200 = "0.1.3"
kotlin = "1.9.23"
kotlinx-binaryCompatibilityValidator = "0.18.1"
kotlin-metadata-jvm = "2.0.0"
preprocessor = "289955506"
asm = "9.9.1"
guava = "33.0.0-jre"

[libraries]
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-binaryCompatibilityValidator = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "kotlinx-binaryCompatibilityValidator" }
kotlinx-metadata-jvm = { module = "org.jetbrains.kotlin:kotlin-metadata-jvm", version.ref = "kotlin-metadata-jvm" }
preprocessor = { module = "com.github.replaymod:preprocessor", version.ref = "preprocessor" }
asm = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
archloom = { module = "gg.essential.loom:gg.essential.loom.gradle.plugin", version.ref = "archloom" }
archloomPack200 = { module = "dev.architectury.architectury-pack200:dev.architectury.architectury-pack200.gradle.plugin", version.ref = "archloomPack200" }
