[versions]
archloom = "1.4.13"
archloomPack200 = "0.1.3"
kotlin = "1.8.21"
kotlinx-binaryCompatibilityValidator = "0.13.1"
kotlinx-metadata-jvm = "0.7.0"
proguard = "7.2.0"
preprocessor = "b09f534"
asm = "9.3"
guava = "30.1.1-jre"

[libraries]
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-binaryCompatibilityValidator = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "kotlinx-binaryCompatibilityValidator" }
kotlinx-metadata-jvm = { module = "org.jetbrains.kotlinx:kotlinx-metadata-jvm", version.ref = "kotlinx-metadata-jvm" }
proguard = { module = "com.guardsquare:proguard-gradle", version.ref = "proguard" }
preprocessor = { module = "com.github.replaymod:preprocessor", version.ref = "preprocessor" }
asm = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
archloom = { module = "gg.essential.loom:gg.essential.loom.gradle.plugin", version.ref = "archloom" }
archloomPack200 = { module = "dev.architectury.architectury-pack200:dev.architectury.architectury-pack200.gradle.plugin", version.ref = "archloomPack200" }
