[versions]
archloom = "1.6.16"
archloomPack200 = "0.1.3"
kotlin = "1.9.23"
kotlinx-binaryCompatibilityValidator = "0.13.1"
kotlinx-metadata-jvm = "0.9.0"
preprocessor = "c2041a3"
asm = "9.6"
guava = "33.0.0-jre"

[libraries]
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-binaryCompatibilityValidator = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "kotlinx-binaryCompatibilityValidator" }
kotlinx-metadata-jvm = { module = "org.jetbrains.kotlinx:kotlinx-metadata-jvm", version.ref = "kotlinx-metadata-jvm" }
preprocessor = { module = "com.github.replaymod:preprocessor", version.ref = "preprocessor" }
asm = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
archloom = { module = "gg.essential.loom:gg.essential.loom.gradle.plugin", version.ref = "archloom" }
archloomPack200 = { module = "dev.architectury.architectury-pack200:dev.architectury.architectury-pack200.gradle.plugin", version.ref = "archloomPack200" }
